Service_Station/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('Station_management.urls', 'Station_management'), namespace='Station_management')),
]

Station_management/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.main_page, name='main'),
    path('clients/', views.clients_search, name='search'),
    path('registration/', views.registration_view, name='registration'),
    path('registration_procedure/', views.registration_procedure, name='registration_procedure'),
    path('<str:first_name>/<int:id>/', views.client_card, name='client_card'),
]

Station_management/models.py
from django.db import models
from django.shortcuts import reverse
from phonenumber_field.modelfields import PhoneNumberField
from .validators import name_validator, make_validator, year_validator, vin_validator,order_amount_validator, order_date_validator



class ClientManager(models.Manager):
    def addClient(self, first_name, last_name, date_of_birth, address, phone, email):
        client = self.create(first_name=first_name, last_name=last_name, date_of_birth=date_of_birth, address=address, phone=phone, email=email)
        return client

class Clients(models.Model): 
    first_name = models.CharField(max_length=25, validators=[name_validator])
    last_name = models.CharField(max_length = 25, validators=[name_validator])
    date_of_birth = models.DateField()
    address = models.CharField(max_length = 150)
    phone = PhoneNumberField(unique=True) 
    email = models.EmailField(unique=True)

    objects = ClientManager()

    class Meta: 
        ordering = ['last_name', 'first_name']
        verbose_name_plural = 'Clients'

    def __str__(self):
        return '{} {}'.format(self.first_name, self.last_name)

    def get_absolute_url(self):
        from .views import clients_search
        return reverse('Station_management:client_card', args=[self.first_name, self.id])


class Cars(models.Model):
    owner = models.ForeignKey('Clients', related_query_name = 'Cars', on_delete = models.CASCADE) 
    make = models.CharField(max_length = 50, validators=[make_validator])
    car_model = models.CharField(max_length = 70)
    year = models.IntegerField(validators = [year_validator]) 
    vin = models.CharField(max_length = 17, unique=True, validators=[vin_validator]) 

    class Meta: 
        ordering = ['make', 'car_model']
        verbose_name_plural = 'Cars'

    def __str__(self):
        return self.vin


class Orders(models.Model): 
    ORDER_STATUSES = [
        ('COMP', 'Completed'),
        ('INPR', 'In Progress'),
        ('CANC', 'Cancelled')
    ]
    car = models.ForeignKey('Cars', related_name = 'Orders', on_delete = models.CASCADE)
    date = models.DateField(validators=[order_date_validator])
    order_amount = models.IntegerField(validators=[order_amount_validator])
    order_status = models.CharField(max_length = 1, choices = ORDER_STATUSES)

    class Meta: 
        ordering = ['-date']
        verbose_name_plural = 'Orders'

Station_management/forms.py
from django import forms
from django.forms import ModelForm
from django.core.validators import validate_email
from .validators import name_validator, ValidationError
from .models import Clients

class SearchClientForm(forms.Form):
    search_field = forms.CharField(widget=forms.TextInput(attrs={'placeholder': 'Enter full name'}))

# class RegistrationForm(forms.Form):
#     first_name_field = forms.CharField(label="First name", validators=[name_validator])
#     last_name_field = forms.CharField(label="Last name", validators=[name_validator])
#     dob_field = forms.DateField(label="Date of birth", widget=forms.DateInput(attrs={'placeholder': 'YYYY-MM-DD'}))
#     address_field = forms.CharField(label="Address")
#     phone_field = forms.CharField(label="Phone number")
#     email_field = forms.CharField(label="Email", validators=[validate_email])


class RegistrationForm(ModelForm):   
    class Meta:
        model = Clients
        fields = '__all__'
        widgets = {
            'date_of_birth': forms.TextInput(attrs={'placeholder': 'YYYY-MM-DD'})
        }
        help_texts = {
            'first_name': 'Only latin letters.'
        }

    def clean_phone(self):
        phone = self.cleaned_data.get('phone')
        if len(phone)<7:
            raise ValidationError('Enter a valid phone number.')
        elif Clients.objects.filter(phone=phone):
            raise ValidationError('This phone number is already registered.')
        return phone

    def clean_email(self):
        email = self.cleaned_data.get('email')
        if Clients.objects.filter(email=email):
            raise ValidationError('This email is already registered.')
        return email

Station_management/views.py
from django.shortcuts import render, get_list_or_404, get_object_or_404, HttpResponse, redirect
from .models import Clients, Cars, Orders
from .forms import SearchClientForm, RegistrationForm
from django.db.models import Q

def main_page(request):
    form = SearchClientForm()
    return render(request, 'Station_management/base.html', {'form':form})

def clients_search(request):
    form = SearchClientForm(request.POST)
    if form.is_valid():
        full_name = form.cleaned_data['search_field']
    full_name_list=full_name.split(' ')
    search_result = get_list_or_404(Clients, Q(first_name=full_name_list[0]) & Q(last_name=full_name_list[1]))
    return render(request, 'Station_management/clients.html', {
         'search_result': search_result
    })

def registration_view(request):
    form = RegistrationForm()
    return render(request, 'Station_management/registration.html', {'form':form})

def registration_procedure(request):
    form = RegistrationForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            form.save()
            return HttpResponse(content=b'Fine!')
    
        return render(request, 'Station_management/registration.html', {'form':form})

def client_card(request, first_name, id):
    client = get_object_or_404(Clients, id=id, first_name=first_name)
    client_cars = Cars.objects.filter(owner = client.id)
    return render(request, 'Station_management/client_card.html', {'client':client, 'client_cars':client_cars})

Station_management/templates/Station_management/base.html
{% extends 'Station_management/index.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="window">
        <div>
            <p>
                Check among registered clients
            </p>
        </div>
        <form action="{% url "Station_management:search" %}" method="post" class="search_form">
            {% csrf_token %}
            {{form.search_field}}
            <input type="submit" value="Check">
        </form>
        <a class="registration_button" href="{% url "Station_management:registration" %}">
            <div>New client registration</div>
        </a>
    </div>
{% endblock %}

Station_management/templates/Station_management/client_card.html
{% extends 'Station_management/index.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="window">
        <table class="cars-table">
            <caption>{{client.first_name}} {{client.last_name}}'s cars</caption>
                <thead class="cars-table-head">
                  <tr>
                    <th>Make</th>
                    <th>Model</th>
                    <th>Year</th>
                    <th>VIN</th>
                  </tr>
                </thead>
                <tbody>
                    {% for car in client_cars %}
                        <tr>
                            <td>{{ car.make }}</td>
                            <td>{{ car.car_model }}</td>
                            <td>{{ car.year }}</td>
                            <td>{{ car.vin }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        <a href="{% url "Station_management:main" %}" class="registration_button homepage-button">
            <div>Homepage</div>
        </a>
    </div>
{% endblock %}

Station_management/templates/Station_management/clients.html
{% extends 'Station_management/index.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="overlay-clients">
        <h2>Search results:</h2>
        {% for result in search_result %}
            <li class="search-result-option">
                <a href="{{result.get_absolute_url}}">{{result.first_name}} {{result.last_name}} (Phone number: {{result.phone}})</a>
            </li>
        {% endfor %}
        <a href="{% url "Station_management:main" %}" class="registration_button homepage-button centration">
            <div>Homepage</div>
        </a>
    </div>
{% endblock %}

Station_management/templates/Station_management/index.html
{% load static from staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <link rel="stylesheet" href="{% static "css/style.css" %}">
  <link href="https://fonts.googleapis.com/css?family=Roboto&display=swap" rel="stylesheet">
</head>
<body>
    <div class="overlay"> 
        {% block content %}
        {% endblock %}
    </div>
</body>
</html>

Station_management/templates/Station_management/registration.html
{% extends 'Station_management/index.html' %}
{% load static from staticfiles %}

{% block content %}
    <div class="window">
        <form action="{% url "Station_management:registration_procedure" %}" method="post" class="reg_form">
            {% csrf_token %}
            {% for field in form %}
                <li class="form-field-item">
                    <span>{{field.label}}</span>
                    {%if form.errors %}
                        {% for error in field.errors %}
                            <div class="form-error-message">{{error}}</div>
                        {% endfor %}
                    {% endif %}
                </li>
                <li >{{field}}</li>
            {% endfor %}
            <li class="form-field-item"><input type="submit" value="Register"></li>
        </form>
        <a href="{% url "Station_management:main" %}" class="registration_button homepage-button">
            <div>Homepage</div>
        </a>
    </div>
{% endblock %}